### PR TITLE
Improve package

### PR DESCRIPTION
**Pull request by vixalien**
- Update dependencies
- Use esbuild instead of webpack & babel
- move output to `dist` folder

pros of using esbuild of webpack & babel:

- 4 less packages
- smaller file sizes
- extremely fast compilation times

### CODE REVIEW

**Comment by vixalien** [comment]
It is important to note that I didn't change anything in the code (the API remains the same) and the package can be used in the exact same way as before. I just gave it some love.

**Comment by Amareis** [comment]
Thank you! I also think about typescript support, but currently don't have much energy to support arc.

**Comment by Amareis** [comment]
Published as 0.6.0 (with single fix for broken test)

**Comment by vixalien** [comment]
What is arc??

**Comment by Amareis** [comment]
> What is arc??

another-rest-client, of course

**Comment by vixalien** [comment]
Oh. I can rewrite it into TypeScript but it will need to use the original `typescript` library by microsoft because esbuild doesn't produce declaration files. And I believe the `typescript` package uses babel (which is slow) and this will lead to using multiple build tools in the same app.

It may be a better idea to produce declaration files manually. However do note that I don't really understand testing so I can't make a test file for the declaration file (I will use typescript to create it, then remove the typescript dependency)

**Comment by Amareis** [comment]
Typescript doesn't use babel. It slower than esbuild, of course, but not indeed on ARC scale (one file and one lib... 0.1 second or 0.5 second isn't much important).

**Comment by vixalien** [comment]
Alright. I find it odd that you use `yarn` in the readme but `npm` in package.json scripts

**Comment by Amareis** [comment]
> Alright. I find it odd that you use `yarn` in the readme but `npm` in package.json scripts

There is no any npm in package.json as i can see.. And yarn was added in readme after your PR.

**Comment by vixalien** [comment]
Hello, I found a problem: I can't get typescript declarations for the `minivents` package because of an apparent error in the package.json's `types` field. I created a PR but no feedback yet. I was wondering if we could embed the declaration for the package.

We can also even remove the `minivents` package and use the `EventTarget` or `EventEmitter` APIs.

I think `EventTarget` is more viable as it is also present on browsers but is newer on Node (I think it was introduced in Node 15 but polyfills exist naturally) and also would change the API i.e using: `{add|remove}EventListener` instead of `on|off`.

The other alternative is using `EventEmitter` which was in Node since the olden times. It uses the exact same api as `minievents` (`on|off`).

[I think this is an interesting section from the Node docs comparing the two](https://nodejs.org/api/events.html#nodeeventtarget-vs-eventemitter)

**Comment by Amareis** [comment]
Hmm. EventTarget is good enough if add on/off shortcuts (to preserve current api). But we can just copy minevents souce code direct in repo and rewerite it to ts, it is really small.

**Comment by Amareis** [comment]
Ok, I make it (and added ts, also convert readme to ascii doc and changed build to move all umd-specific constructions to it).

**Comment by vixalien** [comment]
But you didn't add types for arc did you?

**Comment by Amareis** [comment]
Yep, i make it now. Need to change api slightly (divide encoders/decoders from options)

**Comment by vixalien** [comment]
good work.

**Comment by Amareis** [comment]
Ok, so i fixed main class types, but not types for resources, need some thinking.

**Comment by vixalien** [comment]
what do you mean 'types for resources'?

**Comment by Amareis** [comment]
api.res('cookies') returns resource object, which you are using to make requests. And it should be typed well for subresources (so need to infer types from api scheme, which is provided to res)

**Comment by Amareis** [comment]
Woah, it was easier than i think. Typescript support added, released as 0.7.0! Pay attention to docs, you need to use `withRes` instead of `res` with it! Custom shortcuts not working with ts yet (shortcutted resources not appeared in types), so I think how to make it properly

**Comment by Amareis** [comment]
@vixalien thank you for some motivation to revive arc! As is can see, all alternative packages pointed in readme is archived now, so I feel some responsibility for developers who want use their rest apis with comfort :)

**Pull request merged**
